---
permalink: expansion/task_adding_node_locked_licenses.html 
sidebar: sidebar 
keywords: cluster, feature, node-locked, license, entitle, functionality, add, add node-locked licenses 
summary: Si el clúster tiene funciones que utilizan licencias de bloqueo de nodo, debe asegurarse de que se hayan instalado licencias bloqueadas de nodo para los nuevos nodos. 
---
= Añada licencias de bloqueo de nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si el clúster tiene funciones que utilizan licencias de bloqueo de nodo (que solo otorgan autorización a nodos específicos de la funcionalidad de licencia), debe asegurarse de que se hayan instalado licencias de bloqueo de nodo para los nuevos nodos. Debe añadir las licencias antes de que los nodos se unieran al clúster.

.Pasos
. Para añadir cada clave de licencia, utilice `system license add` comando.
+
[listing]
----
cluster1::> system license add -license-code AAAAAAAAAAAAAA
----
. Para ver las licencias existentes, utilice `system license show` comando.
+
[listing]
----
cluster1::> system license show

Serial Number: 9-99-999999
Owner: cluster1
Package           Type    Description           Expiration
----------------- ------- --------------------- --------------------
Base              site    Cluster Base License  -
NFS               license NFS License           -
CIFS              license CIFS License          -
...
----
. Revise el resultado y compruebe que se muestra una licencia de bloqueo de nodo para todos los números de serie, incluidos los números de serie de los nodos nuevos y existentes.

